### ISSUE TITLE
Color setting for the error message

### ISSUE THREAD

**Issue by umer-shahzaddar** [estruyf/playwright-mail-reporter#1]
hi, is there any way to change the color used in the error message?
now it is using white and the message cannot be seen.

<img width="746" alt="Screenshot 2024-12-04 at 13 25 57" src="https://github.com/user-attachments/assets/cf19d410-2761-46d6-b9e7-e7fdb8757b73">

**Comment by estruyf** [comment]
Thanks @umer-shahzaddar for opening the issue.

This should be resolved in version 0.0.8.

![image](https://github.com/user-attachments/assets/768f5867-c2b1-4014-bda3-5575b2d6b4ba)
